// Our icon pack: the lucide glyphs a plane can take, by name, in loose groups.
//
// Explicit, not lucide's whole set: importing every icon to look names up
// would put all of them in the bundle. Every icon a registered Plane or the
// shell names is in here. A name that is not is no icon at all, and the
// caller falls back to the default (see ./parse.ts).
//
// Names are lucide's own kebab names. `keywords` is extra words the picker's
// search matches on, beyond the name and the group.

import {
	Activity,
	Anchor,
	Archive,
	Atom,
	Bell,
	Book,
	Bookmark,
	BookOpen,
	Boxes,
	Braces,
	Briefcase,
	Bug,
	Building2,
	Calculator,
	Calendar,
	Camera,
	ChartColumn,
	ChartLine,
	ChartPie,
	Clipboard,
	Clock,
	Cloud,
	Code,
	Coffee,
	Cog,
	Coins,
	Compass,
	Contact,
	Cpu,
	Crown,
	Database,
	Diamond,
	Feather,
	File,
	FileText,
	Film,
	Flag,
	Flame,
	Folder,
	FolderOpen,
	Gamepad2,
	Gauge,
	Gem,
	Gift,
	GitBranch,
	Globe,
	Handshake,
	Hash,
	Headphones,
	Heart,
	Hexagon,
	House,
	Image,
	Inbox,
	Kanban,
	Key,
	Layers,
	Leaf,
	Library,
	Lightbulb,
	Link,
	List,
	ListChecks,
	ListTodo,
	Lock,
	type LucideIcon,
	Mail,
	Map as MapIcon,
	MapPin,
	MessageSquare,
	MessagesSquare,
	Mic,
	Moon,
	Mountain,
	Music,
	Network,
	Newspaper,
	NotebookPen,
	Package,
	Palette,
	Paperclip,
	PenTool,
	Phone,
	Plane,
	Puzzle,
	Rocket,
	Search,
	Server,
	Shield,
	Sigma,
	Smile,
	Sparkles,
	Sprout,
	SquareCheckBig,
	SquareTerminal,
	Star,
	StickyNote,
	Store,
	Sun,
	Table,
	Tag,
	Target,
	Timer,
	Trees,
	TrendingUp,
	Trophy,
	Tv,
	User,
	Users,
	Wallet,
	Workflow,
	Wrench,
	Zap,
} from "lucide-react";

/** The pack's groups, in the order the picker shows them. */
export const PACK_GROUPS = [
	{ id: "files", label: "Files" },
	{ id: "work", label: "Work" },
	{ id: "data", label: "Data" },
	{ id: "dev", label: "Dev" },
	{ id: "media", label: "Media" },
	{ id: "people", label: "People" },
	{ id: "places", label: "Places" },
	{ id: "symbols", label: "Symbols" },
] as const;

export type PackGroup = (typeof PACK_GROUPS)[number]["id"];

export type PackIcon = {
	/** lucide's kebab name, what `lucide:<name>` stores. */
	name: string;
	Icon: LucideIcon;
	group: PackGroup;
	/** Extra search words, space separated. */
	keywords: string;
};

/** What a plane with no icon of its own shows. */
export const DEFAULT_ICON_NAME = "file-text";

type Entry = readonly [name: string, Icon: LucideIcon, keywords?: string];

const PACK: Record<PackGroup, readonly Entry[]> = {
	files: [
		["file-text", FileText, "document page note"],
		["file", File, "document blank"],
		["folder", Folder, "directory"],
		["folder-open", FolderOpen, "directory"],
		["notebook-pen", NotebookPen, "journal notes write"],
		["book-open", BookOpen, "read docs guide"],
		["book", Book, "read"],
		["library", Library, "books shelf"],
		["archive", Archive, "box old"],
		["inbox", Inbox, "mail tray"],
		["clipboard", Clipboard, "paste"],
		["sticky-note", StickyNote, "memo"],
		["bookmark", Bookmark, "save"],
		["paperclip", Paperclip, "attach"],
		["newspaper", Newspaper, "news article"],
	],
	work: [
		["briefcase", Briefcase, "job work"],
		["list", List, "items"],
		["list-todo", ListTodo, "tasks todo"],
		["list-checks", ListChecks, "tasks done"],
		["square-check-big", SquareCheckBig, "done task checkbox"],
		["calendar", Calendar, "date schedule"],
		["clock", Clock, "time"],
		["timer", Timer, "time stopwatch"],
		["target", Target, "goal aim"],
		["flag", Flag, "milestone"],
		["kanban", Kanban, "board"],
		["rocket", Rocket, "launch ship"],
		["lightbulb", Lightbulb, "idea"],
		["trophy", Trophy, "win award"],
	],
	data: [
		["activity", Activity, "pulse runs"],
		["chart-line", ChartLine, "graph"],
		["chart-column", ChartColumn, "graph bar"],
		["chart-pie", ChartPie, "graph"],
		["trending-up", TrendingUp, "growth"],
		["gauge", Gauge, "meter speed"],
		["database", Database, "storage store"],
		["table", Table, "grid spreadsheet"],
		["layers", Layers, "stack"],
		["sigma", Sigma, "sum math"],
		["calculator", Calculator, "math"],
		["hash", Hash, "number"],
	],
	dev: [
		["cpu", Cpu, "chip processor worker"],
		["code", Code, "program"],
		["square-terminal", SquareTerminal, "shell console cli"],
		["braces", Braces, "json code"],
		["bug", Bug, "debug issue"],
		["git-branch", GitBranch, "version"],
		["server", Server, "host"],
		["cloud", Cloud, "remote"],
		["network", Network, "graph nodes"],
		["workflow", Workflow, "flow pipeline"],
		["boxes", Boxes, "containers"],
		["package", Package, "box module"],
		["puzzle", Puzzle, "plugin extension"],
		["wrench", Wrench, "tool fix"],
		["cog", Cog, "settings gear"],
		["zap", Zap, "fast power bolt"],
		["key", Key, "secret"],
		["lock", Lock, "secure private"],
		["shield", Shield, "security"],
	],
	media: [
		["image", Image, "picture photo"],
		["camera", Camera, "photo"],
		["film", Film, "movie video"],
		["music", Music, "audio song"],
		["headphones", Headphones, "audio listen"],
		["mic", Mic, "audio voice record"],
		["palette", Palette, "art colour design"],
		["pen-tool", PenTool, "design draw"],
		["tv", Tv, "screen watch"],
		["gamepad-2", Gamepad2, "game play"],
	],
	people: [
		["user", User, "person me profile"],
		["users", Users, "team group people"],
		["contact", Contact, "person card"],
		["mail", Mail, "email letter"],
		["message-square", MessageSquare, "chat comment"],
		["messages-square", MessagesSquare, "chat conversation"],
		["phone", Phone, "call"],
		["smile", Smile, "happy face"],
		["heart", Heart, "love like"],
		["handshake", Handshake, "deal partner"],
	],
	places: [
		["house", House, "home"],
		["building-2", Building2, "office company"],
		["store", Store, "shop"],
		["globe", Globe, "world web"],
		["map", MapIcon, "travel"],
		["map-pin", MapPin, "location place"],
		["compass", Compass, "explore direction"],
		["plane", Plane, "travel flight"],
		["mountain", Mountain, "nature"],
		["trees", Trees, "nature forest"],
		["sun", Sun, "day weather"],
		["moon", Moon, "night"],
	],
	symbols: [
		["star", Star, "favourite"],
		["sparkles", Sparkles, "magic new"],
		["flame", Flame, "fire hot"],
		["leaf", Leaf, "nature plant"],
		["sprout", Sprout, "grow plant"],
		["coffee", Coffee, "drink break"],
		["gift", Gift, "present"],
		["bell", Bell, "notify alert"],
		["hexagon", Hexagon, "shape"],
		["diamond", Diamond, "shape"],
		["atom", Atom, "science"],
		["anchor", Anchor, "harbour"],
		["feather", Feather, "light write"],
		["crown", Crown, "king"],
		["gem", Gem, "jewel"],
		["tag", Tag, "label"],
		["link", Link, "url chain"],
		["search", Search, "find"],
		["wallet", Wallet, "money"],
		["coins", Coins, "money"],
	],
};

/** Every icon in the pack, grouped in `PACK_GROUPS` order. */
export const PACK_ICONS: readonly PackIcon[] = PACK_GROUPS.flatMap(({ id }) =>
	PACK[id].map(([name, Icon, keywords = ""]) => ({ name, Icon, group: id, keywords })),
);

const BY_NAME = new Map(PACK_ICONS.map((icon) => [icon.name, icon]));

/** The pack's icon of that kebab name, if the pack has one. */
export function packIcon(name: string): PackIcon | undefined {
	return BY_NAME.get(name);
}
